<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Models\Food;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $food = [
            // Gujarat Grill -> soup -> Tomato Soup
            [
                'restaurants_id' => '1',
                'categorys_id' => '1',
                'subcategorys_id' => '1',
                'name' => 'Tomato Soup',
                'price' => '55',
                'discription' => 'Tomato soup is a soup with tomatoes as the primary ingredient. It can be served hot or cold, and may be made in a variety of ways.',
                'image' => 'Tomato.jpeg',
                'image2' => 'Tomato.jpeg',
                'image3' => 'Tomato.jpeg',
                'slug' => 'tomato-soup',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> soup ->  Flavors Special Soup
            [
                'restaurants_id' => '1',
                'categorys_id' => '1',
                'subcategorys_id' => '2',
                'name' => 'Flavors Special Soup',
                'price' => '60',
                'discription' => 'Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, milk, or water.',
                'image' => 'flavors.jpeg',
                'image2' => 'flavors.jpeg',
                'image3' => 'flavors.jpeg',
                'slug' => 'flavors-special-soup',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> soup -> Manchow Soup
            [
                'restaurants_id' => '1',
                'categorys_id' => '1',
                'subcategorys_id' => '3',
                'name' => 'Manchow Soup',
                'price' => '108',
                'discription' => 'The origin of Manchow soup is Meghalaya. It is a dark brown soup prepared with various vegetables, scallions, and chicken, thickened with broth and corn flour, and flavored with generous doses of soy sauce, salt, garlic, chili peppers and, predominantly, ginger.',
                'image' => 'Manchow.jpeg',
                'image2' => 'Manchow.jpeg',
                'image3' => 'Manchow.jpeg',
                'slug' => 'manchow-soup',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Gujarat Grill -> Salad -> Fresh Salad
            [
                'restaurants_id' => '1',
                'categorys_id' => '2',
                'subcategorys_id' => '4',
                'name' => 'Fresh Salad',
                'price' => '45',
                'discription' => 'A salad is a dish consisting of mixed pieces of food, typically with at least one raw ... little success to encourage his fellow Britons to eat fresh salad greens.',
                'image' => 'Fresh.jpg',
                'image2' => 'Fresh.jpg',
                'image3' => 'Fresh.jpg',
                'slug' => 'fresh-salad',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> Salad -> Chana Chat
            [
                'restaurants_id' => '1',
                'categorys_id' => '2',
                'subcategorys_id' => '5',
                'name' => 'Chana Chat',
                'price' => '80',
                'discription' => 'Chana chaat is a tasty, tangy and easy variety of chaat snack made with white chickpeas (chana or chole), spices, herbs, onions, tomatoes and lemon.',
                'image' => 'Chana Chat.jpeg',
                'image2' => 'Chana Chat.jpeg',
                'image3' => 'Chana Chat.jpeg',
                'slug' => 'chana-chat',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> Salad -> Apple and Sprout Salad.
            [
                'restaurants_id' => '1',
                'categorys_id' => '2',
                'subcategorys_id' => '6',
                'name' => 'Apple and Sprout Salad',
                'price' => '100',
                'discription' => 'Raw brussels sprouts can stand up to the boldest and most assertive of flavors. Pair the shredded sprouts with a garlicky lemon dressing, plenty of aged Parmesan and crushed  toasted walnuts.',
                'image' => 'Apple and Sprout Salad..jpg',
                'image2' => 'Apple and Sprout Salad..jpg',
                'image3' => 'Apple and Sprout Salad..jpg',
                'slug' => 'apple-and-sprout-salad',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Gujarat Grill -> Dessert -> Ras Gulla
            [
                'restaurants_id' => '1',
                'categorys_id' => '3',
                'subcategorys_id' => '7',
                'name' => 'Ras Gulla',
                'price' => '85',
                'discription' => 'Rasgulla is a South Asian syrupy dessert popular in the Indian subcontinent and regions with South Asian diaspora.',
                'image' => 'Ras Gulla.jpeg',
                'image2' => 'Ras Gulla.jpeg',
                'image3' => 'Ras Gulla.jpeg',
                'slug' => 'ras-gulla',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> Dessert -> Gulab Jamun
            [
                'restaurants_id' => '1',
                'categorys_id' => '3',
                'subcategorys_id' => '8',
                'name' => 'Gulab Jamun',
                'price' => '195',
                'discription' => 'Gulab jamun is an Indian dessert of fried dough balls that are soaked in a sweet, sticky sugar syrup. ',
                'image' => 'Gulab Jamun.jpeg',
                'image2' => '',
                'image3' => 'Gulab Jamun.jpeg',
                'slug' => 'gulab-jamun',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Gujarat Grill -> Dessert -> Fruit Custard
            [
                'restaurants_id' => '1',
                'categorys_id' => '3',
                'subcategorys_id' => '9',
                'name' => 'Fruit Custard',
                'price' => '200',
                'discription' => 'Fruit custard is one of those desserts that I have grown up having along with gajar halwa, rice kheer, besan ladoo. fruit custard and jelly used to take a prime position in the desserts mom would make.',
                'image' => 'Fruit Custard.jpg',
                'image2' => 'Fruit Custard.jpg',
                'image3' => 'Fruit Custard.jpg',
                'slug' => 'fruit-custard',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            
            // palatian -> Noodles -> Hakka Noodles
            [
                'restaurants_id' => '2',
                'categorys_id' => '4',
                'subcategorys_id' => '10',
                'name' => 'Hakka Noodles',
                'price' => '300',
                'discription' => 'Fruit custard is one of those desserts that I have grown up having along with gajar halwa, rice kheer, besan ladoo. fruit custard and jelly used to take a prime position in the desserts mom would make.',
                'image' => 'Hakka Noodles.jpeg',
                'image2' => 'Hakka Noodles.jpeg',
                'image3' => 'Hakka Noodles.jpeg',
                'slug' => 'hakka-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Noodles -> Schezwan Noodles
            [
                'restaurants_id' => '2',
                'categorys_id' => '4',
                'subcategorys_id' => '11',
                'name' => 'Schezwan Noodles',
                'price' => '250',
                'discription' => 'A popular and flavoured noodles recipe made with thin noodles and schezwan sauce. it is popular street food in india which can be served as a party starter or even as a meal for lunch and dinner.',
                'image' => 'Schezwan.jpeg',
                'image2' => 'Schezwan.jpeg',
                'image3' => 'Schezwan.jpeg',
                'slug' => 'sechezwan-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Noodles -> Soba Noodles
            [
                'restaurants_id' => '2',
                'categorys_id' => '4',
                'subcategorys_id' => '12',
                'name' => 'Soba Noodles',
                'price' => '200',
                'discription' => 'Soba noodles are made from buckwheat flour and wheat flour and have a slightly nutty, earthy taste.  it is popular street food in india.',
                'image' => 'Soba.jpeg',
                'image2' => 'Soba.jpeg',
                'image3' => 'Soba.jpeg',
                'slug' => 'soba-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // palatian -> Charcoal Grill -> Paneer Tikka
            [
                'restaurants_id' => '2',
                'categorys_id' => '5',
                'subcategorys_id' => '13',
                'name' => 'Paneer Tikka',
                'price' => '180',
                'discription' => 'Paneer Tikka is a popular and delicious tandoori snack where paneer (Indian cottage cheese cubes) are marinated in a spiced yogurt-based marinade, arranged on skewers and grilled in the oven.',
                'image' => 'Paneer Tikka.jpegTandoori Broccoli.jpeg',
                'image2' => 'Paneer Tikka.jpegTandoori Broccoli.jpeg',
                'image3' => 'Paneer Tikka.jpegTandoori Broccoli.jpeg',
                'slug' => 'paneer-tikka',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Charcoal Grill -> Tandoori Broccoli
            [
                'restaurants_id' => '2',
                'categorys_id' => '5',
                'subcategorys_id' => '14',
                'name' => 'Tandoori Broccoli',
                'price' => '210',
                'discription' => 'Tandoori Broccoli and Gobhi is a fusion recipe you must try for a salubrious diet. This tandoor recipe is prepared by marinating Cauliflower and Broccoli in a mixture made with hung curd, kasoori methi and chaat masala.',
                'image' => 'Tandoori Broccoli.jpeg',
                'image2' => 'Tandoori Broccoli.jpeg',
                'image3' => 'Tandoori Broccoli.jpeg',
                'slug' => 'tandoori-broccoli',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Charcoal Grill -> Mushroom Cheese Melt
            [
                'restaurants_id' => '2',
                'categorys_id' => '5',
                'subcategorys_id' => '15',
                'name' => 'Mushroom Cheese Melt',
                'price' => '200',
                'discription' => 'It’s the best of the best of the best. It’s a Mushroom Melt. Or a Mushroom Grilled Cheese.',
                'image' => 'Mushroom Cheese Melt.jpg',
                'image2' => 'Mushroom Cheese Melt.jpg',
                'image3' => 'Mushroom Cheese Melt.jpg',
                'slug' => 'mushroom-cheese-melt',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Rice -> Special Vegetable Fried Rice
            [
                'restaurants_id' => '2',
                'categorys_id' => '6',
                'subcategorys_id' => '16',
                'name' => 'Special Vegetable Fried Rice',
                'price' => '150',
                'discription' => 'veg fried rice recipe | vegetable fried rice | chinese fried rice with detailed photo and video recipe.',
                'image' => 'Special Vegetable Fried Rice.jpeg',
                'image2' => 'Special Vegetable Fried Rice.jpeg',
                'image3' => 'Special Vegetable Fried Rice.jpeg',
                'slug' => 'special-vegetable-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Rice -> Egg Fried Rice
            [
                'restaurants_id' => '2',
                'categorys_id' => '6',
                'subcategorys_id' => '17',
                'name' => 'Egg Fried Rice',
                'price' => '300',
                'discription' => 'Fried rice is a dish of cooked rice that has been stir-fried in a wok or a frying pan and is usually mixed with other ingredients such as eggs',
                'image' => 'Egg Fried Rice.jpeg',
                'image2' => 'Egg Fried Rice.jpeg',
                'image3' => 'Egg Fried Rice.jpeg',
                'slug' => 'egg-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // palatian -> Rice -> Manchurian Fried Rice
            [
                'restaurants_id' => '2',
                'categorys_id' => '6',
                'subcategorys_id' => '18',
                'name' => 'Manchurian Fried Rice',
                'price' => '400',
                'discription' => 'a classical fusion recipe made by tossing the long grain rice in a manchurian sauce. basically a combination of 2 indo chinese recipe',
                'image' => 'Manchurian Fried Rice.jpeg',
                'image2' => 'Manchurian Fried Rice.jpeg',
                'image3' => 'Manchurian Fried Rice.jpeg',
                'slug' => 'manchurian-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            
            // TGB -> Puff -> Veg. Puff
            [
                'restaurants_id' => '3',
                'categorys_id' => '7',
                'subcategorys_id' => '19',
                'name' => 'Veg. Puff',
                'price' => '30',
                'discription' => 'Along with puff pastry recipe I had also got some requests to post a veg puff recipe. So sharing a recipe which is tasty and gives you the feeling of having the Veg puffs like the ones you get in Indian bakeries.',
                'image' => 'Veg. Puff.jpeg',
                'image2' => 'Veg. Puff.jpeg',
                'image3' => 'Veg. Puff.jpeg',
                'slug' => 'veg-puff',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> Puff -> Cheese Puff
            [
                'restaurants_id' => '3',
                'categorys_id' => '7',
                'subcategorys_id' => '20',
                'name' => 'Cheese Puff',
                'price' => '50',
                'discription' => 'Cheese puffs were invented independently by two companies in the United States during the 1930s. According to one account, Edward Wilson noticed strings of puffed corn oozing from flaking machines',
                'image' => 'Cheese Puff.jpeg',
                'image2' => 'Cheese Puff.jpeg',
                'image3' => 'Cheese Puff.jpeg',
                'slug' => 'cheese-puff',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> Puff -> Kadhai Paneer Puff
            [
                'restaurants_id' => '3',
                'categorys_id' => '7',
                'subcategorys_id' => '21',
                'name' => 'Kadhai Paneer Puff',
                'price' => '60',
                'discription' => 'The buttery and flaky crust and the super delicious paneer stuffing made this one of my favorite snacks to have while in India.',
                'image' => 'Kadhai Paneer Puff.jpeg',
                'image2' => 'Kadhai Paneer Puff.jpeg',
                'image3' => 'Kadhai Paneer Puff.jpeg',
                'slug' => 'kadhai-paneer-puff',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            
            // TGB -> Sundaes -> Choclate Lava
            [
                'restaurants_id' => '3',
                'categorys_id' => '8',
                'subcategorys_id' => '22',
                'name' => 'Choclate Lava',
                'price' => '350',
                'discription' => 'chocolate lava cake is the batter which has warmed during baking but hasn’t fully set. The key is to bake just until the sides are set but the inside is still molten.',
                'image' => 'Choclate Lava.jpeg',
                'image2' => 'Choclate Lava.jpeg',
                'image3' => 'Choclate Lava.jpeg',
                'slug' => 'choclate-lava',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> Sundaes -> Pastry
            [
                'restaurants_id' => '3',
                'categorys_id' => '8',
                'subcategorys_id' => '23',
                'name' => 'Pastry',
                'price' => '200',
                'discription' => 'Pastry is a dough of flour, water and shortening that may be savoury or sweetened. Sweetened pastries are often described as bakers confectionery.',
                'image' => 'Pastry.jpeg',
                'image2' => 'Pastry.jpeg',
                'image3' => 'Pastry.jpeg',
                'slug' => 'pastry',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> Sundaes -> Sizzling Brownie
            [
                'restaurants_id' => '3',
                'categorys_id' => '8',
                'subcategorys_id' => '24',
                'name' => 'Sizzling Brownie',
                'price' => '100',
                'discription' => 'Sizzling brownie is a dessert available in India, made popular by cafes and restaurants of Mumbai & Kerala. It is a chocolate brownie',
                'image' => 'Sizzling Brownie.jpeg',
                'image2' => 'Sizzling Brownie.jpeg',
                'image3' => 'Sizzling Brownie.jpeg',
                'slug' => 'sizzling-brownie',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // TGB -> sandwich -> American Club Sandwich
            [
                'restaurants_id' => '3',
                'categorys_id' => '9',
                'subcategorys_id' => '25',
                'name' => 'American Club Sandwich',
                'price' => '',
                'discription' => '',
                'image' => 'American Club.jpeg',
                'image2' => 'American Club.jpeg',
                'image3' => 'American Club.jpeg',
                'slug' => 'american-club',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> sandwich -> Cheese Chutney Sandwich
            [
                'restaurants_id' => '3',
                'categorys_id' => '9',
                'subcategorys_id' => '26',
                'name' => 'Cheese Chutney Sandwich',
                'price' => '500',
                'discription' => 'A club sandwich, also called a clubhouse sandwich, is a sandwich of bread (traditionally toasted), sliced cooked poultry, ham or fried bacon.',
                'image' => 'Cheese Chutney Sandwich.jpeg',
                'image2' => 'Cheese Chutney Sandwich.jpeg',
                'image3' => 'Cheese Chutney Sandwich.jpeg',
                'slug' => 'cheese-chutney-sandwich',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // TGB -> sandwich -> Vegetable Cheese Melt
            [
                'restaurants_id' => '3',
                'categorys_id' => '9',
                'subcategorys_id' => '27',
                'name' => 'Vegetable Cheese Melt',
                'price' => '350',
                'discription' => 'There’s nothing more simple to make and satisfying to enjoy than a warm, crisp and gooey cheese sandwich. Here I share two ways with step-by-step photos for how to prepare an easy grilled cheese sandwich recipe in less than 20 minutes.',
                'image' => 'Vegetable Cheese Melt.jpeg',
                'image2' => 'Vegetable Cheese Melt.jpeg',
                'image3' => 'Vegetable Cheese Melt.jpeg',
                'slug' => 'vegetable-cheese-melt',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Burger king -> Burger -> Crispy Veg Burger
            [
                'restaurants_id' => '4',
                'categorys_id' => '10',
                'subcategorys_id' => '28',
                'name' => 'Crispy Veg Burger',
                'price' => '200',
                'discription' => 'Mixed Vegetable and Cheese Sandwich is a must try sandwich recipe. It is a healthy breakfast recipe that you can try during the weekneds or pack for lunch during the weekdays.',
                'image' => 'Crispy Veg Burger.jpeg',
                'image2' => 'Crispy Veg Burger.jpeg',
                'image3' => 'Crispy Veg Burger.jpeg',
                'slug' => 'crispy-veg-burger',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Burger -> Bk Classic Veg
            [
                'restaurants_id' => '4',
                'categorys_id' => '10',
                'subcategorys_id' => '29',
                'name' => 'Bk Classic Veg',
                'price' => '55',
                'discription' => 'A hamburger (or burger for short) is a food, typically considered a sandwich, consisting of one or more cooked patties—usually ground meat, typically beef—placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked or flame broiled. ... A hamburger topped with cheese is called a cheeseburger.',
                'image' => 'Bk Classic Veg.jpeg',
                'image2' => 'Bk Classic Veg.jpeg',
                'image3' => 'Bk Classic Veg.jpeg',
                'slug' => 'bk-classic-veg',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Burger -> Crispy Veg Double Patty
            [
                'restaurants_id' => '4',
                'categorys_id' => '10',
                'subcategorys_id' => '30',
                'name' => 'Crispy Veg Double Patty',
                'price' => '60',
                'discription' => 'A hamburger (or burger for short) is a food, typically considered a sandwich, consisting of one or more cooked patties—usually ground meat, typically beef—placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked or flame broiled. ... A hamburger topped with cheese is called a cheeseburger.',
                'image' => 'Crispy Veg Double Patty.jpeg',
                'image2' => 'Crispy Veg Double Patty.jpeg',
                'image3' => 'Crispy Veg Double Patty.jpeg',
                'slug' => 'crispy-veg-patty',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Burger king -> Cold Drinks -> Pepsi
            [
                'restaurants_id' => '4',
                'categorys_id' => '11',
                'subcategorys_id' => '31',
                'name' => 'Pepsi',
                'price' => '35',
                'discription' => 'Soft drink, any of a class of nonalcoholic beverages, usually but not necessarily carbonated, normally containing a natural or artificial sweetening agent, edible acids, natural or artificial flavours, and sometimes juice.',
                'image' => 'pepsi.jpeg',
                'image2' => 'pepsi.jpeg',
                'image3' => 'pepsi.jpeg',
                'slug' => 'pepsi',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Cold Drinks -> Choclate Thik Shake
            [
                'restaurants_id' => '4',
                'categorys_id' => '11',
                'subcategorys_id' => '32',
                'name' => 'Choclate Thik Shake',
                'price' => '90',
                'discription' => 'Soft drink, any of a class of nonalcoholic beverages, usually but not necessarily carbonated, normally containing a natural or artificial sweetening agent, edible acids, natural or artificial flavours, and sometimes juice.',
                'image' => 'Choclate Thik Shake.jpeg',
                'image2' => 'Choclate Thik Shake.jpeg',
                'image3' => 'Choclate Thik Shake.jpeg',
                'slug' => 'choclate-thik-shake',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Cold Drinks -> Berry Blast Thik Shake
            [
                'restaurants_id' => '4',
                'categorys_id' => '11',
                'subcategorys_id' => '33',
                'name' => 'Berry Blast Thik Shake',
                'price' => '155',
                'discription' => 'Soft drink, any of a class of nonalcoholic beverages, usually but not necessarily carbonated, normally containing a natural or artificial sweetening agent, edible acids, natural or artificial flavours, and sometimes juice.',
                'image' => 'Berry Blast Thik Shake.jpeg',
                'image2' => 'Berry Blast Thik Shake.jpeg',
                'image3' => 'Berry Blast Thik Shake.jpeg',
                'slug' => 'berry-blast-thik-shake',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Burger king -> Creamy Sundaes -> Chocolate Sundaes
            [
                'restaurants_id' => '4',
                'categorys_id' => '12',
                'subcategorys_id' => '34',
                'name' => 'Chocolate Sundaes',
                'price' => '90',
                'discription' => 'A sundae ( /ˈsʌndeɪ, ˈsʌndi/) is an ice cream dessert that typically consists of one or more scoops of ice cream topped with sauce or syrup and in some cases other toppings such as: sprinkles, whipped cream, marshmallows, peanuts, maraschino cherries, or other fruits (e.g. bananas and pineapple in a banana split).',
                'image' => 'Chocolate Sundaes.jpeg',
                'image2' => 'Chocolate Sundaes.jpeg',
                'image3' => 'Chocolate Sundaes.jpeg',
                'slug' => 'choclate-sundaes',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Creamy Sundaes -> Strawberry Sundaes
            [
                'restaurants_id' => '4',
                'categorys_id' => '12',
                'subcategorys_id' => '35',
                'name' => 'Strawberry Sundaes',
                'price' => '108',
                'discription' => 'A sundae ( /ˈsʌndeɪ, ˈsʌndi/) is an ice cream dessert that typically consists of one or more scoops of ice cream topped with sauce or syrup and in some cases other toppings such as: sprinkles, whipped cream, marshmallows, peanuts, maraschino cherries, or other fruits (e.g. bananas and pineapple in a banana split).',
                'image' => 'Strawberry Sundaes.jpeg',
                'image2' => 'Strawberry Sundaes.jpeg',
                'image3' => 'Strawberry Sundaes.jpeg',
                'slug' => 'strawberry-sundaes',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Burger king -> Creamy Sundaes -> Turtle Sundaes
            [
                'restaurants_id' => '4',
                'categorys_id' => '12',
                'subcategorys_id' => '36',
                'name' => 'Turtle Sundaes',
                'price' => '120',
                'discription' => 'A sundae ( /ˈsʌndeɪ, ˈsʌndi/) is an ice cream dessert that typically consists of one or more scoops of ice cream topped with sauce or syrup and in some cases other toppings such as: sprinkles, whipped cream, marshmallows, peanuts, maraschino cherries, or other fruits (e.g. bananas and pineapple in a banana split).',
                'image' => 'Turtle Sundaes.jpeg',
                'image2' => 'Turtle Sundaes.jpeg',
                'image3' => 'Turtle Sundaes.jpeg',
                'slug' => 'turtle-sundaes',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Zomato -> Fried Rise -> Noodlestir Fried Rice
            [
                'restaurants_id' => '5',
                'categorys_id' => '13',
                'subcategorys_id' => '37',
                'name' => 'Noodlestir Fried Rice',
                'price' => '45',
                'discription' => 'a dish of boiled or steamed rice that is stir-fried typically with soy sauce, beaten egg, chopped meat, and vegetables.',
                'image' => 'Noodlestir Fried Rice.jpeg',
                'image2' => 'Noodlestir Fried Rice.jpeg',
                'image3' => 'Noodlestir Fried Rice.jpeg',
                'slug' => 'noodlestir-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Fried Rise -> lighter Fried Rice
            [
                'restaurants_id' => '5',
                'categorys_id' => '13',
                'subcategorys_id' => '38',
                'name' => 'lighter Fried Rice',
                'price' => '80',
                'discription' => 'a dish of boiled or steamed rice that is stir-fried typically with soy sauce, beaten egg, chopped meat, and vegetables.',
                'image' => 'lighter Fried Rice.jpeg',
                'image2' => 'lighter Fried Rice.jpeg',
                'image3' => 'lighter Fried Rice.jpeg',
                'slug' => 'lighter-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Fried Rise -> Yang Chow Fried Rice
            [
                'restaurants_id' => '5',
                'categorys_id' => '13',
                'subcategorys_id' => '39',
                'name' => 'Yang Chow Fried Rice',
                'price' => '85',
                'discription' => 'a dish of boiled or steamed rice that is stir-fried typically with soy sauce, beaten egg, chopped meat, and vegetables.',
                'image' => 'Yang Chow Fried Rice.jpeg',
                'image2' => 'Yang Chow Fried Rice.jpeg',
                'image3' => 'Yang Chow Fried Rice.jpeg',
                'slug' => 'yang-chow-fried-rice',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Zomato -> Noodles -> Hokkien Noodles
            [
                'restaurants_id' => '5',
                'categorys_id' => '14',
                'subcategorys_id' => '40',
                'name' => 'Hokkien Noodles',
                'price' => '110',
                'discription' => 'noodle, a cooked egg-and-flour paste prominent in European and Asian cuisine, generally distinguished from pasta by its elongated ribbonlike form. Noodles are commonly used to add body and flavour to broth soups. They are commonly boiled or sautéed and served with sauces and meats or baked in casseroles.',
                'image' => 'Hokkien Noodles.jpeg',
                'image2' => 'Hokkien Noodles.jpeg',
                'image3' => 'Hokkien Noodles.jpeg',
                'slug' => 'hokkien-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Noodles -> Rice Stick Noodles
            [
                'restaurants_id' => '5',
                'categorys_id' => '14',
                'subcategorys_id' => '41',
                'name' => 'Rice Stick Noodles',
                'price' => '120',
                'discription' => 'noodle, a cooked egg-and-flour paste prominent in European and Asian cuisine, generally distinguished from pasta by its elongated ribbonlike form. Noodles are commonly used to add body and flavour to broth soups. They are commonly boiled or sautéed and served with sauces and meats or baked in casseroles.',
                'image' => 'Rice Stick Noodles.jpeg',
                'image2' => 'Rice Stick Noodles.jpeg',
                'image3' => 'Rice Stick Noodles.jpeg',
                'slug' => 'rice-stick-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Noodles -> Udon Noodles
            [
                'restaurants_id' => '5',
                'categorys_id' => '14',
                'subcategorys_id' => '42',
                'name' => 'Udon Noodles',
                'price' => '130',
                'discription' => 'noodle, a cooked egg-and-flour paste prominent in European and Asian cuisine, generally distinguished from pasta by its elongated ribbonlike form. Noodles are commonly used to add body and flavour to broth soups. They are commonly boiled or sautéed and served with sauces and meats or baked in casseroles.',
                'image' => 'Udon Noodles.jpeg',
                'image2' => 'Udon Noodles.jpeg',
                'image3' => 'Udon Noodles.jpeg',
                'slug' => 'udon-noodles',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Zomato -> Rolls -> Manchurian Roll
            [
                'restaurants_id' => '5',
                'categorys_id' => '15',
                'subcategorys_id' => '43',
                'name' => 'Manchurian Roll',
                'price' => '130',
                'discription' => 'A variety of rolls are found in Europe, from white rolls made with wheat flour, to dark rolls containing mostly rye flour. Many variants include spices, such as coriander and cumin, or nuts. Also common are bread rolls containing or garnished with whole seeds such as sesame, poppy, pumpkin or sunflower.',
                'image' => 'Manchurian Roll.jpeg',
                'image2' => 'Manchurian Roll.jpeg',
                'image3' => 'Manchurian Roll.jpeg',
                'slug' => 'cheese-chill-manchuria-roll',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Rolls -> Cheese Chill Manchurian Roll
            [
                'restaurants_id' => '5',
                'categorys_id' => '15',
                'subcategorys_id' => '44',
                'name' => 'Cheese Chill Manchurian Roll',
                'price' => '140',
                'discription' => 'A variety of rolls are found in Europe, from white rolls made with wheat flour, to dark rolls containing mostly rye flour. Many variants include spices, such as coriander and cumin, or nuts. Also common are bread rolls containing or garnished with whole seeds such as sesame, poppy, pumpkin or sunflower.',
                'image' => 'Cheese Chill Manchurian Roll.jpeg',
                'image2' => 'Cheese Chill Manchurian Roll.jpeg',
                'image3' => 'Cheese Chill Manchurian Roll.jpeg',
                'slug' => 'cheese-chill-manchurian-roll',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Zomato -> Rolls -> Paneer Roll
            [
                'restaurants_id' => '5',
                'categorys_id' => '15',
                'subcategorys_id' => '45',
                'name' => 'Paneer Roll',
                'price' => '150',
                'discription' => 'A variety of rolls are found in Europe, from white rolls made with wheat flour, to dark rolls containing mostly rye flour. Many variants include spices, such as coriander and cumin, or nuts. Also common are bread rolls containing or garnished with whole seeds such as sesame, poppy, pumpkin or sunflower.',
                'image' => 'Paneer Roll.jpeg',
                'image2' => 'Paneer Roll.jpeg',
                'image3' => 'Paneer Roll.jpeg',
                'slug' => 'paneer-roll',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Papillon -> Pasta -> White Souce Pasta
            [
                'restaurants_id' => '6',
                'categorys_id' => '16',
                'subcategorys_id' => '46',
                'name' => 'White Souce Pasta',
                'price' => '115',
                'discription' => 'White sauce pasta is one of the easiest pasta recipes that you can make. It is also one of the most popular pasta recipes. You can make the classic white sauce pasta or make it more colorful and nutritious by adding some vegetables.',
                'image' => 'White Souce Pasta.jpeg',
                'image2' => 'White Souce Pasta.jpeg',
                'image3' => 'White Souce Pasta.jpeg',
                'slug' => 'white-souce-pasta',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Pasta -> Macaroni Pasta
            [
                'restaurants_id' => '6',
                'categorys_id' => '16',
                'subcategorys_id' => '47',
                'name' => 'Macaroni Pasta',
                'price' => '80',
                'discription' => 'Macaroni is dry pasta shaped like narrow tubes. Made with durum wheat, macaroni is commonly cut in short lengths; curved macaroni may be referred to as elbow macaroni.',
                'image' => 'Macaroni Pasta.jpeg',
                'image2' => 'Macaroni Pasta.jpeg',
                'image3' => 'Macaroni Pasta.jpeg',
                'slug' => 'macroni-pasta',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Pasta -> Desi Masala Pasta
            [
                'restaurants_id' => '6',
                'categorys_id' => '16',
                'subcategorys_id' => '48',
                'name' => 'Desi Masala Pasta',
                'price' => '60',
                'discription' => 'This Indian style desi pasta features tender penne pasta coated with flavorful, Indian spiced creamy tomato sauce, lots of veggies, Italian seasoning and fresh cilantro. Just imagine all that goodness!',
                'image' => 'Desi Masala Pasta.jpeg',
                'image2' => 'Desi Masala Pasta.jpeg',
                'image3' => 'Desi Masala Pasta.jpeg',
                'slug' => 'desi-masala-pasta',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Papillon -> Snacks -> Bitterballen
            [
                'restaurants_id' => '6',
                'categorys_id' => '17',
                'subcategorys_id' => '49',
                'name' => 'Bitterballen',
                'price' => '110',
                'discription' => 'Bitterballen (plural of bitterbal) are a Dutch meat-based snack, made by making a very thick stew thickened with roux and beef stock and generously loaded with meat, refrigerating the stew until it firms, and then rolling the thick mixture into balls which then get breaded and fried.',
                'image' => 'Bitterballen.jpeg',
                'image2' => 'Bitterballen.jpeg',
                'image3' => 'Bitterballen.jpeg',
                'slug' => 'bitterballen',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Snacks -> Veg. Cutlet
            [
                'restaurants_id' => '6',
                'categorys_id' => '17',
                'subcategorys_id' => '50',
                'name' => 'Veg. Cutlet',
                'price' => '110',
                'discription' => 'Vegetable Cutlet also called as veg cutlet are crisp, savory, tender patties made with a mix of hearty veggies, savory spices, fresh herbs and crispy breadcrumbs. Cutlet recipe is a popular snack in Indian cuisine and there are so many ways to make them. These vegan vegetable cutlet are pan fried to keep them healthy, but as you prefer you can deep fry or shallow fry.',
                'image' => 'Veg. Cutlet.jpeg',
                'image2' => 'Veg. Cutlet.jpeg',
                'image3' => 'Veg. Cutlet.jpeg',
                'slug' => 'veg-cutlet',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Snacks -> Paneer Pakoda
            [
                'restaurants_id' => '6',
                'categorys_id' => '17',
                'subcategorys_id' => '51',
                'name' => 'Paneer Pakoda',
                'price' => '170',
                'discription' => 'Paneer pakora is a deep fried popular north Indian snack with a crispy outer layer of gram flour and soft and moist paneer from the inside. Paneer slices (or cubes) are coated with the batter of gram flour(besan) and then deep fried until crispy. These pakoras can be made in two different ways- 1).',
                'image' => 'Paneer Pakoda.jpeg',
                'image2' => 'Paneer Pakoda.jpeg',
                'image3' => 'Paneer Pakoda.jpeg',
                'slug' => 'paneer-pakoda',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // Papillon -> Moctails -> Green Hornet
            [
                'restaurants_id' => '6',
                'categorys_id' => '18',
                'subcategorys_id' => '52',
                'name' => 'Green Hornet',
                'price' => '300',
                'discription' => 'Combine all ingredients, except tonic, and shake with ice. Strain into an ice-filled Collins glass and top with tonic.',
                'image' => 'Green Hornet.jpeg',
                'image2' => 'Green Hornet.jpeg',
                'image3' => 'Green Hornet.jpeg',
                'slug' => 'green-hornet',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Moctails -> Mastani
            [
                'restaurants_id' => '6',
                'categorys_id' => '18',
                'subcategorys_id' => '53',
                'name' => 'Mastani',
                'price' => '540',
                'discription' => 'Discover a hedonistic wilderness and be lead on a mesmerizing journey of taste, sound and colour at MASTI every Saturday with the new ‘Mischievous Monkey Brunch’',
                'image' => 'Mastani.jpeg',
                'image2' => 'Mastani.jpeg',
                'image3' => 'Mastani.jpeg',
                'slug' => 'mastani',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            // Papillon -> Moctails -> Apple Fizz
            [
                'restaurants_id' => '6',
                'categorys_id' => '18',
                'subcategorys_id' => '54',
                'name' => 'Apple Fizz',
                'price' => '15',
                'discription' => 'Bubbly, sweet, and tangy, it is the best fizzy drink you can ever have. Water, Sugar, Apple Juice Concentrate 1.90% (Equivalent to 12.7% Apple Juice Reconstituted), Carbon Dioxide (INS290), Acidity Regulators (INS296, INS330), Permitted Class II Preservatives (INS211, INS224, INS202) and Antioxidant (INS300).',
                'image' => 'Apple Fizz.jpeg',
                'image2' => 'Apple Fizz.jpeg',
                'image3' => 'Apple Fizz.jpeg',
                'slug' => 'apple-fizz',
                'status' => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];
        Food::insert($food);
    }
}
